oauth2Proxy:
  image:
    repository: quay.io/oauth2-proxy/oauth2-proxy
    tag: v7.9.0-alpine
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 4180
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  args:
    - --some-args-for-oauth2-proxy-here

yarr:
  image:
    repository: ghcr.io/nkanaev/yarr
    tag: v2.5
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 7070
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 128Mi

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "8"
  hosts:
    - host: yarr.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: yarr-tls
      hosts:
        - yarr.example.com
