apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "yarr.fullname" . }}
  labels:
    {{- include "yarr.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "yarr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "yarr.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: oauth2-proxy
          image: {{ .Values.oauth2Proxy.image.repository }}:{{ .Values.oauth2Proxy.image.tag }}
          imagePullPolicy: {{ .Values.oauth2Proxy.image.pullPolicy }}
          ports:
          - containerPort: {{ .Values.oauth2Proxy.service.port }}
          {{- with .Values.oauth2Proxy.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command: {{ .Values.oauth2Proxy.command }}
          args:
            {{- toYaml .Values.oauth2Proxy.args | nindent 12 }}
          volumeMounts:
            {{- with .Values.extraSecrets }}
            {{- range . }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              readOnly: {{ .readOnly | default true }}
            {{- end }}
            {{- end }}

        - name: yarr
          image: {{ .Values.yarr.image.repository }}:{{ .Values.yarr.image.tag }}
          imagePullPolicy: {{ .Values.yarr.image.pullPolicy }}
          ports:
          - containerPort: {{ .Values.yarr.service.port }}
          {{- with .Values.yarr.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: YARR_ADDR
              value: "127.0.0.1:7070"
            - name: YARR_DB
              value: "/data/yarr.db"
          volumeMounts:
            - name: {{ include "yarr.fullname" . }}-data
              mountPath: /data
            {{- with .Values.extraSecrets }}
            {{- range . }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              readOnly: {{ .readOnly | default true }}
            {{- end }}
            {{- end }}
      volumes:
        - name: yarr-data
          persistentVolumeClaim:
            claimName: yarr-data
        {{- with .Values.extraSecrets }}
        {{- range . }}
        - name: {{ .name }}
          secret:
            secretName: {{ .secretName }}
          defaultMode: {{ .defaultMode | default 420 }}
        {{- end }}
        {{- end }}
