apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "yarr.fullname" . }}-data
  labels:
    {{- include "yarr.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi